//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.BlazorWebApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.BlazorWebApp.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string CommonReturn {
            get {
                return ResourceManager.GetString("CommonReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CommonSave {
            get {
                return ResourceManager.GetString("CommonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string LoginAccess {
            get {
                return ResourceManager.GetString("LoginAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirm.
        /// </summary>
        public static string LoginConfirmPassword {
            get {
                return ResourceManager.GetString("LoginConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string LoginDontHaveAnAccount {
            get {
                return ResourceManager.GetString("LoginDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginEnter {
            get {
                return ResourceManager.GetString("LoginEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string LoginForgetPassword {
            get {
                return ResourceManager.GetString("LoginForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here..
        /// </summary>
        public static string LoginRegisterHere {
            get {
                return ResourceManager.GetString("LoginRegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string LoginSignUp {
            get {
                return ResourceManager.GetString("LoginSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized: check your email/password..
        /// </summary>
        public static string LoginUnauthorized {
            get {
                return ResourceManager.GetString("LoginUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ended....
        /// </summary>
        public static string LogoutSessionEnded {
            get {
                return ResourceManager.GetString("LogoutSessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to login page.
        /// </summary>
        public static string LogoutToLoginPage {
            get {
                return ResourceManager.GetString("LogoutToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already taken..
        /// </summary>
        public static string RegisterDuplicateEmail {
            get {
                return ResourceManager.GetString("RegisterDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Error.
        /// </summary>
        public static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email..
        /// </summary>
        public static string RegisterInvalidEmail {
            get {
                return ResourceManager.GetString("RegisterInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string RegisterPasswordRequiresDigit {
            get {
                return ResourceManager.GetString("RegisterPasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string RegisterPasswordRequiresLower {
            get {
                return ResourceManager.GetString("RegisterPasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non alphanumeric character..
        /// </summary>
        public static string RegisterPasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("RegisterPasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must use at least 1 different characters..
        /// </summary>
        public static string RegisterPasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("RegisterPasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string RegisterPasswordRequiresUpper {
            get {
                return ResourceManager.GetString("RegisterPasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least 6 characters..
        /// </summary>
        public static string RegisterPasswordTooShort {
            get {
                return ResourceManager.GetString("RegisterPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string TopBarAccountSettings {
            get {
                return ResourceManager.GetString("TopBarAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string TopBarGreeting {
            get {
                return ResourceManager.GetString("TopBarGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string TopBarLogout {
            get {
                return ResourceManager.GetString("TopBarLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string TopBarMyProfile {
            get {
                return ResourceManager.GetString("TopBarMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string TopBarViewProfile {
            get {
                return ResourceManager.GetString("TopBarViewProfile", resourceCulture);
            }
        }
    }
}
